//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
USERES("A406_R41.res");
USEUNIT("..\source\AdSrmgr.pas");
USEUNIT("..\source\AwFax.pas");
USEUNIT("..\source\AdExcept.pas");
USEUNIT("..\source\AdFax.pas");
USEUNIT("..\source\ADFAXCTL.pas");
USEUNIT("..\source\Adfaxcvt.pas");
USEUNIT("..\source\AdFaxPrn.pas");
USEUNIT("..\source\Adfview.pas");
USEUNIT("..\source\AdMeter.pas");
USEUNIT("..\source\AdPacket.pas");
USEUNIT("..\source\AdPort.pas");
USEUNIT("..\source\AdProtcl.pas");
USEUNIT("..\source\ADPSTAT.pas");
USEUNIT("..\source\AdSelCom.pas");
USEUNIT("..\source\AdSocket.pas");
USEUNIT("..\source\AdStatLt.pas");
USEUNIT("..\source\AdTapi.pas");
USEUNIT("..\source\adtsel.pas");
USEUNIT("..\source\Adtstat.pas");
USEUNIT("..\source\AdTUtil.pas");
USEUNIT("..\source\Adwnport.pas");
USEUNIT("..\source\Adwutil.pas");
USEUNIT("..\source\Adxdial.pas");
USEUNIT("..\source\Adxdown.pas");
USEUNIT("..\source\Adxport.pas");
USEUNIT("..\source\Adxprot.pas");
USEUNIT("..\source\Adxup.pas");
USEUNIT("..\source\AwAbsPcl.pas");
USEUNIT("..\source\AwAscii.pas");
USEUNIT("..\source\AwFaxCvt.pas");
USEUNIT("..\source\AwKermit.pas");
USEUNIT("..\source\AwTPcl.pas");
USEUNIT("..\source\AwUser.pas");
USEUNIT("..\source\AwWin32.pas");
USEUNIT("..\source\AwWnSock.pas");
USEUNIT("..\source\AwXmodem.pas");
USEUNIT("..\source\AwYmodem.pas");
USEUNIT("..\source\AwZmodem.pas");
USEUNIT("..\source\OoMisc.pas");
USEUNIT("..\source\Awabsfax.pas");
USEUNIT("..\source\Adfstat.pas");
USEUNIT("..\source\Adfpstat.pas");
USEUNIT("..\source\AwFView.pas");
USEUNIT("..\source\AdPager.pas");
USEUNIT("..\source\Adftp.pas");
USEUNIT("..\source\AdScript.pas");
USEUNIT("..\source\ADTrmEmu.pas");
USEUNIT("..\source\ADTrmPsr.pas");
USEUNIT("..\source\ADTrmMap.pas");
USEUNIT("..\source\ADTrmBuf.pas");
USEUNIT("..\source\AdRStat.pas");
USEUNIT("..\source\Adras.pas");
USEUNIT("..\source\Adrasutl.pas");
USEUNIT("..\source\Adfaxsrv.pas");
USEUNIT("..\source\Adfidlg.pas");
USEUNIT("..\source\AdGSM.pas");
USEUNIT("..\source\PDrvUnNT.pas");
USEUNIT("..\source\PDrvUni.pas");
USEUNIT("..\source\PDrvInst.pas");
USEUNIT("..\source\PDrvInNT.pas");
USEPACKAGE("vcl40.bpi");
USEUNIT("..\source\AdStMach.pas");
USEUNIT("..\source\AdSapiEn.pas");
USEUNIT("..\source\AdSapiPh.pas");
USEUNIT("..\source\LNSWin32.pas");
USEUNIT("..\source\LNSQueue.pas");
USEPACKAGE("bcbsmp40.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
