//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
USERES("A406_R35.res");
USEPACKAGE("vclx35.bpi");
USEPACKAGE("VCL35.bpi");
USEPACKAGE("bcbsmp35.bpi");
USEUNIT("..\source\AdPStat.pas");
USEUNIT("..\source\AdRStat.pas");
USEUNIT("..\source\AdRas.pas");
USEUNIT("..\source\AdRasUtl.pas");
USEUNIT("..\source\AdFPStat.pas");
USEUNIT("..\source\AdTStat.pas");
USEUNIT("..\source\AdFaxCtl.pas");
USEUNIT("..\source\AdFaxSrv.pas");
USEUNIT("..\source\AdFaxPrn.pas");
USEUNIT("..\source\AdFStat.pas");
USEUNIT("..\source\AdMeter.pas");
USEUNIT("..\source\AdFax.pas");
USEUNIT("..\source\AwFax.pas");
USEUNIT("..\source\AwAbsFax.pas");
USEUNIT("..\source\AdFIDlg.pas");
USEUNIT("..\source\AdFtp.pas");
USEUNIT("..\source\AdFView.pas");
USEUNIT("..\source\AwFView.pas");
USEUNIT("..\source\AdFaxCvt.pas");
USEUNIT("..\source\AwFaxCvt.pas");
USEUNIT("..\source\AdMdm.pas");
USEUNIT("..\source\AdMdmCfg.pas");
USEUNIT("..\source\AdMdmDlg.pas");
USEUNIT("..\source\AdLibMdm.pas");
USEUNIT("..\source\AdXLbMdm.pas");
USEUNIT("..\source\AdXParsr.pas");
USEUNIT("..\source\AdXChrFlt.pas");
USEUNIT("..\source\AdXBase.pas");
USEUNIT("..\source\AdPackEd.pas");
USEUNIT("..\source\AdPager.pas");
USEUNIT("..\source\AdScript.pas");
USEUNIT("..\source\AdWnPort.pas");
USEUNIT("..\source\AwWnsock.pas");
USEUNIT("..\source\AdProtcl.pas");
USEUNIT("..\source\AwYmodem.pas");
USEUNIT("..\source\AwXmodem.pas");
USEUNIT("..\source\AwZmodem.pas");
USEUNIT("..\source\AwKermit.pas");
USEUNIT("..\source\AwAscii.pas");
USEUNIT("..\source\AwAbsPcl.pas");
USEUNIT("..\source\AwTPcl.pas");
USEUNIT("..\source\AdStatLt.pas");
USEUNIT("..\source\AdStMach.pas");
USEUNIT("..\source\AdPacket.pas");
USEUNIT("..\source\ADTrmEmu.pas");
USEUNIT("..\source\ADTrmPsr.pas");
USEUNIT("..\source\ADTrmMap.pas");
USEUNIT("..\source\ADTrmBuf.pas");
USEUNIT("..\source\AdTapi.pas");
USEUNIT("..\source\AdTSel.pas");
USEUNIT("..\source\AdPort.pas");
USEUNIT("..\source\AdTUtil.pas");
USEUNIT("..\source\AdSelCom.pas");
USEUNIT("..\source\AwWin32.pas");
USEUNIT("..\source\AdSocket.pas");
USEUNIT("..\source\AdWUtil.pas");
USEUNIT("..\source\AwUser.pas");
USEUNIT("..\source\AdExcept.pas");
USEUNIT("..\source\AdSrMgr.pas");
USEUNIT("..\source\LNSQueue.pas");
USEUNIT("..\source\LNSQueue.pas");
//USEUNIT("..\source\OoMisc.pas");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
    return 1;
}
//---------------------------------------------------------------------------
